// Central mock data source — used when real pipeline data is absent
// Real data from /data/ takes priority over these values in all API routes

export const MOCK_POSITIONS = [
  {
    ticker: "UNH", company: "UnitedHealth Group", sector: "Healthcare", direction: "long",
    entry_price: 458.20, current_price: 487.50, pct_change: 6.40, pnl_absolute: 2930,
    position_size: 45750, pct_portfolio: 10.0, entry_date: "2026-03-17", conviction: 70,
    status: "hold", setup_type: "Distressed/Turnaround", expected_roi: "25-35%",
  },
  {
    ticker: "DG", company: "Dollar General", sector: "Consumer Discretionary", direction: "long",
    entry_price: 72.40, current_price: 79.85, pct_change: 10.29, pnl_absolute: 3725,
    position_size: 36200, pct_portfolio: 10.0, entry_date: "2026-03-17", conviction: 70,
    status: "hold", setup_type: "Distressed/Turnaround", expected_roi: "30-45%",
  },
  {
    ticker: "EL", company: "Estée Lauder", sector: "Consumer Staples", direction: "long",
    entry_price: 68.90, current_price: 76.20, pct_change: 10.60, pnl_absolute: 3650,
    position_size: 34450, pct_portfolio: 10.0, entry_date: "2026-03-17", conviction: 75,
    status: "hold", setup_type: "Distressed/Turnaround", expected_roi: "25-40%",
  },
  {
    ticker: "CRM", company: "Salesforce", sector: "Technology", direction: "long",
    entry_price: 242.10, current_price: 256.80, pct_change: 6.07, pnl_absolute: 1470,
    position_size: 24210, pct_portfolio: 10.0, entry_date: "2026-03-17", conviction: 70,
    status: "hold", setup_type: "Growth", expected_roi: "20-30%",
  },
  {
    ticker: "MKC", company: "McCormick & Company", sector: "Consumer Staples", direction: "long",
    entry_price: 72.15, current_price: 75.90, pct_change: 5.20, pnl_absolute: 1875,
    position_size: 36075, pct_portfolio: 10.0, entry_date: "2026-03-17", conviction: 70,
    status: "hold", setup_type: "Distressed/Turnaround", expected_roi: "20-30%",
  },
  {
    ticker: "COIN", company: "Coinbase Global", sector: "Financials", direction: "long",
    entry_price: 164.30, current_price: 158.70, pct_change: -3.41, pnl_absolute: -560,
    position_size: 16430, pct_portfolio: 7.5, entry_date: "2026-03-17", conviction: 70,
    status: "hold", setup_type: "Event-Driven", expected_roi: "40-80%",
  },
];

export const MOCK_PORTFOLIO_STATS = {
  total_value: 113090,
  cash: 32885,
  deployed: 67115,
  deployed_pct: 67.1,
  total_pnl_pct: 12.5,
  total_pnl_absolute: 13090,
  daily_pnl_pct: 0.82,
  daily_pnl_absolute: 820,
  active_positions: 6,
  pipeline_status: "success",
  pipeline_last_run: "2026-03-28T14:15:00Z",
};

export const MOCK_PORTFOLIO_HISTORY = [
  { date: "2026-03-03", value: 100000 },
  { date: "2026-03-04", value: 99200 },
  { date: "2026-03-05", value: 100800 },
  { date: "2026-03-06", value: 101500 },
  { date: "2026-03-07", value: 100900 },
  { date: "2026-03-10", value: 102100 },
  { date: "2026-03-11", value: 103400 },
  { date: "2026-03-12", value: 102700 },
  { date: "2026-03-13", value: 104200 },
  { date: "2026-03-14", value: 105800 },
  { date: "2026-03-17", value: 107100 },
  { date: "2026-03-18", value: 108600 },
  { date: "2026-03-19", value: 109200 },
  { date: "2026-03-20", value: 110800 },
  { date: "2026-03-21", value: 111400 },
  { date: "2026-03-24", value: 110900 },
  { date: "2026-03-25", value: 112300 },
  { date: "2026-03-26", value: 113090 },
  { date: "2026-03-27", value: 112600 },
  { date: "2026-03-28", value: 113090 },
];

export const MOCK_SECTOR_ALLOCATION = [
  { sector: "Consumer Staples", value: 20.0, color: "#0EA5E9" },
  { sector: "Healthcare", value: 10.0, color: "#06B6D4" },
  { sector: "Technology", value: 10.0, color: "#8B5CF6" },
  { sector: "Consumer Discretionary", value: 10.0, color: "#F59E0B" },
  { sector: "Financials", value: 7.5, color: "#10B981" },
  { sector: "Cash", value: 32.9, color: "rgba(255,255,255,0.15)" },
  { sector: "Other", value: 9.6, color: "#6B7280" },
];

export const MOCK_DAILY_REPORTS = [
  {
    date: "2026-03-28",
    macro_regime: "RISK-OFF",
    new_positions: 6,
    exits: 0,
    holds: 0,
    increases: 0,
    decreases: 0,
    daily_pnl: "+0.82%",
    summary:
      "Committee identified 6 dislocation long opportunities across Healthcare, Consumer Staples, and Technology sectors amid broad market selloff. VIX at 31 — quality stocks dragged below intrinsic value.",
    narrative: `Today's pipeline run identified a significant dislocation opportunity across multiple sectors. With VIX at 31, the market is pricing in broad fear rather than company-specific deterioration — exactly the environment our forward-looking mandate was designed to exploit.

The Candidate Generator's dislocation screen surfaced 7 S&P 500 constituents down more than 20% in the past month. After full agent analysis, the Committee approved 6 enter-long positions: UNH (70 conviction), DG (70), EL (75), CRM (70), MKC (70), and COIN (70).

UnitedHealth Group is trading at a 28% discount to sector median P/E despite no structural deterioration in its core managed care business. The selloff appears macro-driven, not fundamental. Estée Lauder shows the highest mean reversion score at 82/100 — RSI at 24 (deeply oversold), 31% below SMA200, and volume selling exhaustion detected.

Dollar General and McCormick represent defensive consumer staples with recession-resilient demand profiles. Both are trading at discounts to their 5-year median valuations.

Salesforce's technical picture is mixed, but the fundamental dislocation is clear: trading at forward P/E of 18x vs sector median 28x — a 36% discount with no earnings revision.

The Committee applied the self-challenge rule: all 6 decisions are enter-long in a RISK-OFF regime. Upon re-examination, the mean reversion scores (ranging 55–82) and dislocation signals across Fundamental and Sentiment agents confirmed this is appropriate — these are dislocated quality names, not momentum longs.`,
    agent_findings: [
      { agent: "Macro Analyst", finding: "VIX 31, RISK-OFF — broad selloff presenting dislocation vs genuine deterioration" },
      { agent: "Sector Analyst", finding: "Healthcare and Consumer Staples show strongest forward bias; Tech mixed" },
      { agent: "Institutional Tracker", finding: "Smart money accumulation detected in UNH, EL at current levels" },
      { agent: "News & Catalyst", finding: "No company-specific negative catalysts for any approved position" },
      { agent: "Candidate Generator", finding: "7 dislocation candidates identified; 6 approved after full analysis" },
      { agent: "Fundamental Analyst", finding: "EL: -42% vs intrinsic. UNH: -28% vs sector P/E median. CRM: -36% discount" },
      { agent: "Quant & Technical", finding: "EL mean_reversion_score 82, UNH 71, DG 68 — all showing selling exhaustion" },
      { agent: "Sentiment Analyst", finding: "Negative sentiment classified as lagging on all 6 names — contrarian signal confirmed" },
      { agent: "Memory Agent", finding: "No conflicting prior decisions. Pattern: RISK-OFF dislocation longs — first instance" },
      { agent: "Investment Committee", finding: "4-scenario analysis: all 6 classified Scenario B (dislocation long). Self-challenge passed." },
      { agent: "Trade Executor", finding: "Market closed at execution time. Orders will execute at market open Monday." },
    ],
    decisions: [
      { ticker: "UNH", action: "enter_long", conviction: 70, thesis: "28% below sector P/E median. Mean reversion score 71. Selling exhaustion." },
      { ticker: "DG", action: "enter_long", conviction: 70, thesis: "Consumer defensive, 23% below SMA200. RSI 31. Dislocation opportunity." },
      { ticker: "EL", action: "enter_long", conviction: 75, thesis: "Highest mean reversion score (82). RSI 24. -42% vs peer intrinsic value." },
      { ticker: "CRM", action: "enter_long", conviction: 70, thesis: "Forward P/E 18x vs sector 28x. -36% discount. Contrarian signal active." },
      { ticker: "MKC", action: "enter_long", conviction: 70, thesis: "Recession-resilient staples. 19% below SMA200. Lagging negative sentiment." },
      { ticker: "COIN", action: "enter_long", conviction: 70, thesis: "Dislocation screen hit — 34% drawdown past month. Asymmetric risk/reward." },
    ],
  },
];

export const MOCK_AGENTS = [
  {
    id: "macro",
    name: "Macro Analyst",
    role: "Macro Analyst",
    number: 1,
    personality: "The oracle. Reads the macro so the others don't have to.",
    accuracy: 72,
    current_focus: "Fed rate path and VIX trajectory",
    market_view: "RISK-OFF regime. Policy uncertainty elevated. Dislocation > momentum.",
    recent_activity: "Flagged VIX spike to 31 as dislocation signal, not trend continuation",
    color: "#0EA5E9",
  },
  {
    id: "sector",
    name: "Sector Analyst",
    role: "Sector Analyst",
    number: 2,
    personality: "The context engine. Always knows which sector is worth fighting for.",
    accuracy: 68,
    current_focus: "Healthcare vs Tech relative performance",
    market_view: "Defensives leading. Healthcare dislocation deepest in 3 years.",
    recent_activity: "Upgraded Healthcare to STRONG BUY on sector-relative dislocation",
    color: "#06B6D4",
  },
  {
    id: "institutional",
    name: "Institutional Tracker",
    role: "Institutional Tracker",
    number: 3,
    personality: "The spy. Follows the smart money so you don't have to guess.",
    accuracy: 65,
    current_focus: "13-F filings — healthcare accumulation patterns",
    market_view: "Institutions quietly accumulating UNH, EL at current levels",
    recent_activity: "Detected net buying in UNH by 3 major funds despite price decline",
    color: "#8B5CF6",
  },
  {
    id: "news",
    name: "News & Catalyst",
    role: "News & Catalyst Agent",
    number: 4,
    personality: "The scanner. 10,000 headlines, one signal.",
    accuracy: 63,
    current_focus: "Macro tariff news vs company-specific catalysts",
    market_view: "Current selloff macro-driven, not company-specific. Buy the dip thesis supported.",
    recent_activity: "Confirmed no company-specific negative catalysts for any approved position",
    color: "#F59E0B",
  },
  {
    id: "candidate",
    name: "Candidate Generator",
    role: "Candidate Generator",
    number: 5,
    personality: "The filter. Turns 950 stocks into 50 worth fighting for.",
    accuracy: 74,
    current_focus: "Dislocation screen — S&P 500 members down >20%",
    market_view: "7 quality names at deep discounts. Dislocation is real, not value traps.",
    recent_activity: "Surfaced DG, MKC, UNH — invisible to Phase 1 agents due to low news coverage",
    color: "#10B981",
  },
  {
    id: "fundamental",
    name: "Fundamental Analyst",
    role: "Fundamental Analyst",
    number: 6,
    personality: "The accountant with an opinion. Numbers don't lie, but they do tell stories.",
    accuracy: 71,
    current_focus: "Sector-relative P/E dislocation in Healthcare and Consumer Staples",
    market_view: "EL, UNH, CRM trading well below peer median intrinsic value",
    recent_activity: "EL: -42% vs peer intrinsic. UNH: -28% vs sector P/E median.",
    color: "#EF4444",
  },
  {
    id: "quant",
    name: "Quant & Technical",
    role: "Quant & Technical Analyst",
    number: 7,
    personality: "The mathematician. If it can't be scored, it doesn't exist.",
    accuracy: 76,
    current_focus: "Mean reversion scores across dislocation candidates",
    market_view: "4 of 6 positions showing RSI < 35 and selling exhaustion signals",
    recent_activity: "EL mean_reversion_score 82 — highest in current cohort. RSI 24.",
    color: "#3B82F6",
  },
  {
    id: "sentiment",
    name: "Sentiment Analyst",
    role: "Sentiment Analyst",
    number: 8,
    personality: "The contrarian. When everyone hates it, that's when it gets interesting.",
    accuracy: 69,
    current_focus: "Leading vs lagging sentiment classification",
    market_view: "Current negative sentiment classified as lagging on all 6 positions",
    recent_activity: "Contrarian signal active: consensus still shows 15–40% upside on all 6 names",
    color: "#F97316",
  },
  {
    id: "memory",
    name: "Memory Agent",
    role: "Memory & Pattern Agent",
    number: 9,
    personality: "The historian. Remembers every trade, every mistake, every win.",
    accuracy: 80,
    current_focus: "Building pattern history: RISK-OFF dislocation longs",
    market_view: "First RISK-OFF entry cohort. Pattern history building.",
    recent_activity: "Stored 6 new entry theses. Pattern: dislocation_long_risk_off — new category.",
    color: "#6B7280",
  },
  {
    id: "committee",
    name: "Investment Committee",
    role: "Investment Committee",
    number: 10,
    personality: "The decider. Hears all 9 agents. Makes the call. Owns it.",
    accuracy: 73,
    current_focus: "Scenario B (dislocation long) classification protocol",
    market_view: "6 Scenario B positions. Self-challenge rule passed. Conviction solid.",
    recent_activity: "Applied self-challenge rule — re-examined all positions after all-long initial output. Confirmed.",
    color: "#E11D48",
  },
  {
    id: "executor",
    name: "Trade Executor",
    role: "Trade Executor",
    number: 11,
    personality: "The action. No opinion, no hesitation. The Committee decides, I execute.",
    accuracy: 98,
    current_focus: "6 pending orders — market open Monday",
    market_view: "N/A — executor does not form market views",
    recent_activity: "6 orders queued for Monday market open. Paper trading mode. Alpaca verified.",
    color: "#22C55E",
  },
];

export const MOCK_POSITION_DETAIL = {
  ticker: "EL",
  company: "Estée Lauder Companies",
  sector: "Consumer Staples",
  direction: "long",
  entry_price: 68.90,
  current_price: 76.20,
  pct_change: 10.60,
  pnl_absolute: 3650,
  position_size: 34450,
  pct_portfolio: 10.0,
  entry_date: "2026-03-17",
  conviction: 75,
  scenario: "B",
  setup_type: "Distressed/Turnaround",
  expected_roi: "25-40%",
  investment_thesis:
    "Estée Lauder represents a textbook Scenario B dislocation opportunity. The stock is trading 42% below its peer-group intrinsic value (P/E 11x vs Consumer Staples sector median 19x). This disconnection is entirely macro-driven — the China re-opening trade has partially reversed despite no structural deterioration in core brand equity or distribution. Mean reversion score 82/100 is the highest in the current cohort.",
  investment_thesis_bullets: [
    "Trading at 42% discount to sector P/E median — deepest dislocation in Consumer Staples universe",
    "China revenue headwind is cyclical, not structural — brand equity intact across 150+ countries",
    "New CEO Stéphane de La Faverie with turnaround mandate and 20-year company track record",
    "Mean reversion score 82/100 — RSI 24, selling exhaustion confirmed, institutional accumulation building",
    "Analyst consensus $145 target implies 90% upside from entry; 23 analysts covering with Buy consensus",
  ],
  recommendation: {
    direction: "LONG",
    expected_return_pct: 32,
    conviction: 75,
    stop_loss_note: "Stop at $62 (-10% from entry). ATR × 2.0 = $6.90 below entry — $62 aligns with prior support.",
  },
  agent_scores: [
    { agent: "Macro", score: 62, view: "RISK-OFF. Selloff broad, not EL-specific." },
    { agent: "Sector", score: 78, view: "Consumer Staples holding up — EL dislocation is deepest in sector." },
    { agent: "Institutional", score: 71, view: "Net accumulation detected at current price range." },
    { agent: "News", score: 65, view: "No new negative catalysts. China narrative overhang priced in." },
    { agent: "Fundamental", score: 88, view: "P/E 11x vs sector 19x. -42% peer-relative discount. Strong balance sheet." },
    { agent: "Quant", score: 82, view: "Mean reversion score 82. RSI 24. Selling exhaustion confirmed." },
    { agent: "Sentiment", score: 74, view: "Contrarian signal active. Sentiment lagging. 15+ analysts still bullish." },
    { agent: "Memory", score: 70, view: "No prior EL position. Consumer Staples dislocation pattern: 3/4 success rate." },
    { agent: "Committee", score: 75, view: "Scenario B unanimous. Highest conviction in cohort." },
  ],
  fund_mandate: {
    asset_class: "Equity",
    exchange: "NYSE",
    sector: "Consumer Staples",
    market_cap_figure: "$27B Large Cap",
    avg_daily_volume_usd: "$180M/day",
    geography_flags: {
      russia_exposure: false,
      mongolia_exposure: false,
      cambodia_exposure: false,
      exposure_detail: "Americas 40%, Asia Pacific 35%, EMEA 20%, Other 5%. No sanctioned market exposure.",
    },
    peps_check: { clean: true, notes: "No politically exposed persons identified on management team or board." },
    setup_type: "Distressed/Turnaround",
    float_pct: 98.2,
  },
  mandate_checklist: [
    { item: "Asset class — listed equity (NYSE)", pass: true },
    { item: "Market cap >$1B ($27B Large Cap)", pass: true },
    { item: "Sector in universe (Consumer Staples)", pass: true },
    { item: "Avg daily liquidity >$50M ($180M/day)", pass: true },
    { item: "No Russia / Mongolia / Cambodia revenue exposure", pass: true },
    { item: "PEPs check — management team clean", pass: true },
    { item: "Setup type identified (Distressed/Turnaround)", pass: true },
    { item: "Float % adequate (98.2%)", pass: true },
  ],
  company_info: {
    hq: "New York, USA",
    employees: 48000,
    overview: "Estée Lauder Companies is the global leader in prestige beauty, operating across skincare, makeup, fragrance, and hair care. The company owns 25+ brands including Estée Lauder, Clinique, MAC, La Mer, and Bobbi Brown, sold through department stores, specialty retailers, travel retail, and direct-to-consumer channels globally.",
    revenue_segments: [
      { segment: "Skincare", weight_pct: 57 },
      { segment: "Makeup", weight_pct: 22 },
      { segment: "Fragrance", weight_pct: 14 },
      { segment: "Hair Care", weight_pct: 7 },
    ],
    geography_breakdown: [
      { region: "Americas", pct: 40 },
      { region: "Asia Pacific", pct: 35 },
      { region: "EMEA", pct: 25 },
    ],
  },
  financial_snapshot: {
    historical: [
      { year: "2022", revenue: 17737000000, ebitda: 3198000000, net_income: 2390000000 },
      { year: "2023", revenue: 15910000000, ebitda: 1820000000, net_income: -37000000 },
      { year: "2024", revenue: 15610000000, ebitda: 1102000000, net_income: -562000000 },
    ],
    forward: [
      { year: "2025E", revenue: 15200000000, ebitda: 1400000000, net_income: 220000000, source: "Analyst consensus (10 analysts)" },
      { year: "2026E", revenue: 16800000000, ebitda: 2100000000, net_income: 680000000, source: "Analyst consensus (8 analysts)" },
    ],
  },
  comparables: [
    { ticker: "EL", company: "Estée Lauder", revenue_bn: 15.6, pe_ratio: null as number | null, ps_ratio: null as number | null, ebitda_margin_pct: 7, net_margin_pct: -3.6, de_ratio: 1.8, is_subject: true },
    { ticker: "COTY", company: "Coty Inc.", revenue_bn: 5.8, pe_ratio: null as number | null, ps_ratio: null as number | null, ebitda_margin_pct: 14, net_margin_pct: 2, de_ratio: 3.2 },
    { ticker: "ULTA", company: "Ulta Beauty", revenue_bn: 11.3, pe_ratio: null as number | null, ps_ratio: null as number | null, ebitda_margin_pct: 18, net_margin_pct: 11, de_ratio: 0.4 },
    { ticker: "CHD", company: "Church & Dwight", revenue_bn: 5.9, pe_ratio: null as number | null, ps_ratio: null as number | null, ebitda_margin_pct: 19, net_margin_pct: 12, de_ratio: 1.1 },
    { ticker: "CLX", company: "Clorox", revenue_bn: 7.1, pe_ratio: null as number | null, ps_ratio: null as number | null, ebitda_margin_pct: 15, net_margin_pct: 7, de_ratio: 2.3 },
  ],
  market_analysis: {
    tam_usd: "$150B",
    growth_rate: "7% CAGR through 2028",
    competition_intensity: "High",
    sector_trends: "Prestige beauty outperforming mass market post-pandemic. China re-opening recovery expected H2 2026. Skincare category sustaining premium pricing power with 8% category growth.",
    macro_factors: "USD strength creates headwind on international revenue translation. China consumer confidence at 18-month low — primary driver of stock dislocation. Fed rate path uncertainty limiting multiple expansion.",
  },
  quality_of_earnings: {
    moat: "Wide",
    competitive_advantages: [
      "Iconic brand portfolio with 75+ year heritage and global recognition",
      "Global distribution across 150+ countries with exclusive prestige channel positioning",
      "Premium pricing power — skincare category with 8%+ annual price increases accepted",
      "R&D leadership in skincare with La Mer and Estée Lauder Advanced Night Repair",
    ],
    barriers_to_entry: "Brand equity in luxury beauty requires decades to build. Distribution relationships with premium retailers are exclusive. Consumer trust in prestige products is highly sticky — switching costs are psychological and social.",
    sustainability: "Business model is structurally durable. Current earnings depression is cyclical (China), not structural. FCF generation continues. 40-year dividend growth history intact.",
  },
  management_team: {
    ceo: "Stéphane de La Faverie (appointed Jan 2025) — former Global Brand President of Estée Lauder and Aramis brands. 20+ year company veteran. MBA from INSEAD.",
    track_record: "Previous CEO Fabrizio Freda presided over decade of 10%+ CAGR. De La Faverie promoted from within — positioned as turnaround-focused with deep brand and channel knowledge. No prior CEO-level public company experience.",
    red_flags: null,
  },
  analyst_rating_history: {
    current_consensus: "Buy",
    num_analysts: 23,
    avg_target_price: 145,
    implied_upside_pct: 90,
    trend_24m: "Downgrading",
    summary: "Consensus drifted from Strong Buy (2022 avg target $350) to Buy/Hold (2024) following China slowdown and two profit warnings. Recent upgrades from Goldman Sachs and Barclays as turnaround thesis gains traction at current price.",
  },
  cap_table: {
    institutional_pct: 64,
    insider_pct: 31,
    float_pct: 98,
    major_holders: [
      { name: "Lauder Family Holdings", pct: 31.2 },
      { name: "Vanguard Group", pct: 8.1 },
      { name: "BlackRock Inc.", pct: 6.7 },
      { name: "State Street Corp", pct: 4.2 },
      { name: "T. Rowe Price", pct: 3.1 },
    ],
  },
  setup_checklist: [
    { item: "Setup type", detail: "Distressed/Turnaround — earnings depressed by cyclical China headwind, not structural deterioration" },
    { item: "Revenue CAGR 3yr", detail: "-4.1% CAGR (below 20% threshold) — this is the dislocation, not a disqualifier" },
    { item: "Margin trend", detail: "Contracting (72% → 70% gross margin) — cyclical China mix shift, not structural pricing failure" },
    { item: "Upcoming catalysts", detail: "China PMI recovery, FY2026 guidance reset (May 2026), new premium skincare launches, USD weakening" },
    { item: "FCF positive", detail: "Yes — FCF $400M TTM despite earnings loss. Core business generates cash." },
    { item: "Default risk", detail: "Low — investment grade credit, $2.1B cash, $4.5B revolving credit facility" },
    { item: "Moat strength", detail: "Wide — 25+ iconic brands, 150-country distribution, premium pricing power intact" },
    { item: "Key risks", detail: "China consumer confidence deterioration, margin pressure from inventory destocking, new CEO execution risk" },
  ],
  valuation: {
    trade_type_classification: "Scale-up",
    methodology: "Comps+multiples",
    analyst_consensus_target: 145,
    implied_multiples: "Currently trading P/E 11x TTM vs sector median 19x — 42% discount. On 2026E earnings, forward P/E of 31x — in line with sector, implying recovery already visible to market.",
    is_forecast_realistic: "Conservative — consensus assumes partial China recovery only. Full China recovery would push 2026E net income above current consensus, implying further upside beyond $145.",
    intrinsic_value_estimate: 120,
    expected_roi_2_3yr: "25-40%",
    moic_estimate: "1.25x-1.4x",
  },
  market_timing: "RSI at 24 — extreme oversold, last seen March 2020 and October 2022, both followed by >30% recoveries within 6 months. OBV divergence confirms selling exhaustion: price falling on declining volume. Institutional Tracker confirms net buying by 2 major funds. China PMI catalyst 60-90 day window.",
  review_timeline: [
    { date: "2026-03-17", decision: "enter_long", rationale: "Scenario B — dislocation long. Conviction 75. Position size 10%." },
    { date: "2026-03-18", decision: "hold", rationale: "Thesis intact. Price +1.2%. No new catalysts. Mean reversion trend continuing." },
    { date: "2026-03-19", decision: "hold", rationale: "Sector rotation into defensive staples supporting. Volume normalising." },
    { date: "2026-03-20", decision: "hold", rationale: "RSI recovering from 24 to 31. Not yet overbought. Continue holding." },
    { date: "2026-03-21", decision: "increase", rationale: "Thesis strengthening. Institutional buying confirmed. Increased to 12.5%." },
  ],
  price_history: [
    { date: "2026-02-17", price: 112.30 }, { date: "2026-02-20", price: 108.50 },
    { date: "2026-02-25", price: 103.20 }, { date: "2026-03-01", price: 96.40 },
    { date: "2026-03-05", price: 89.10 }, { date: "2026-03-10", price: 82.30 },
    { date: "2026-03-14", price: 75.60 }, { date: "2026-03-17", price: 68.90 },
    { date: "2026-03-18", price: 69.72 }, { date: "2026-03-19", price: 71.05 },
    { date: "2026-03-20", price: 72.15 }, { date: "2026-03-21", price: 73.90 },
    { date: "2026-03-24", price: 74.20 }, { date: "2026-03-25", price: 75.10 },
    { date: "2026-03-28", price: 76.20 },
  ],
};
